### ISSUE TITLE
syntax error, unexpected $end, expecting keyword_end

### ISSUE THREAD

**Issue by ppoektos** [myaspm/redmine_stats_2#2]
```
Environment:
  Redmine version                3.3.0.stable.15842
  Ruby version                   1.9.3-p327 (2012-11-10) [i686-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': /var/www/rm330/plugins/redmine_stats/init.rb:7: invalid multibyte char (US-ASCII) (SyntaxError)
/var/www/rm330/plugins/redmine_stats/init.rb:7: invalid multibyte char (US-ASCII)
/var/www/rm330/plugins/redmine_stats/init.rb:7: syntax error, unexpected $end, expecting keyword_end
  author 'Mustafa Yılmaz <myaspm@gmail.com>'
                     ^
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /var/www/rm330/lib/redmine/plugin.rb:155:in `block in load'
	from /var/www/rm330/lib/redmine/plugin.rb:146:in `each'
	from /var/www/rm330/lib/redmine/plugin.rb:146:in `load'
	from /var/www/rm330/config/initializers/30-redmine.rb:21:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:180:in `each'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /var/www/rm330/config/environment.rb:14:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from config.ru:4:in `block in <main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/lib/unicorn.rb:44:in `eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/lib/unicorn.rb:44:in `block in builder'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/bin/unicorn_rails:139:in `call'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/bin/unicorn_rails:139:in `block in rails_builder'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/lib/unicorn/http_server.rb:718:in `call'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/lib/unicorn/http_server.rb:718:in `build_app!'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/lib/unicorn/http_server.rb:591:in `init_worker_process'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/lib/unicorn/http_server.rb:611:in `worker_loop'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/lib/unicorn/http_server.rb:142:in `start'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/unicorn-4.5.0/bin/unicorn_rails:209:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/bin/unicorn_rails:19:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/bin/unicorn_rails:19:in `<main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by myaspm** [comment]
Must be fixed, please try it and give feedback thanks!

**Comment by ppoektos** [comment]
I've fixed this myself and it works since then, just reported FYI.
I love this plugin, however output for a 7 years active projects in redmine incorrect in some places.

**Comment by myaspm** [comment]
How did you fix it, i'm curious :D As for your other problem, would you mind giving me a screenshot to make me understand what exactly is the problem? Right now the "since the beginning of time" tab works only since 2016 and thats because i've hard coded that way. It can easily be changed to 1999 or some other year.

**Comment by ppoektos** [comment]
This information is not readable. Maybe it could be better to swap axis and show persons horizontally and order them by amount of sum of issues.
![stats_currentmonth](https://cloud.githubusercontent.com/assets/1829833/20434732/edf1c4dc-adb1-11e6-9105-af895b01d350.png)

**Comment by myaspm** [comment]
Yeah i get it now, well swapping axis seems logical. Let me see what can i do on this issue.

Or is it simply enough to extend the width of the graph to say 750px?
